import { Employee } from '../types';

export const TENANT_ID = 'tenant-arqensial-01';

export const ARQENSIAL_EMPLOYEES: Employee[] = [
  {
    id: 'emp-001',
    tenantId: TENANT_ID,
    empCode: 'AT-1001',
    firstName: 'Sameer',
    lastName: 'Kanojiya',
    fullName: 'Sameer Kanojiya',
    email: 'sameer.kanojiya@arqensial.com',
    phone: '+91 98201 12345',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    role: 'company_admin',
    departmentId: 'dept-hr',
    departmentName: 'HR',
    designation: 'CEO',
    employmentType: 'Full-Time',
    status: 'Active',
    joiningDate: '2023-01-15',
    location: 'Mumbai HQ',
    workShift: 'General Shift (09:30 - 18:30)',
    salaryStructure: {
      annualCTC: 3600000,
      monthlyGross: 300000,
      basic: 150000,
      hra: 60000,
      specialAllowance: 88000,
      conveyance: 2000,
      performanceBonus: 0,
      pfEmployee: 1800,
      pfEmployer: 1800,
      esi: 0,
      professionalTax: 200,
      tdsMonthly: 48000,
      netMonthly: 250000,
    },
    bankDetails: {
      accountHolder: 'Sameer Kanojiya',
      bankName: 'HDFC Bank Ltd',
      accountNumber: '••••••••4812',
      ifscSwift: 'HDFC0000128',
      branch: 'Malad West Branch, Mumbai',
      panNumber: 'AAAPK1029M',
      uanNumber: '10148822001',
    },
    emergencyContacts: [{ name: 'Kavita Kanojiya', relation: 'Spouse', phone: '+91 98201 99999' }],
    documents: [],
    skills: ['Executive Leadership', 'Strategic Planning', 'SaaS Architecture', 'P&L Management'],
    experience: [{ company: 'TechSolutions India', role: 'VP Operations', duration: '2018 - 2022', description: 'Led 150+ engineers' }],
    education: [{ degree: 'B.Tech Computer Science', institution: 'VJTI Mumbai', year: '2014', grade: 'Distinction' }],
    notes: [],
  },
  {
    id: 'emp-002',
    tenantId: TENANT_ID,
    empCode: 'AT-1002',
    firstName: 'Neha',
    lastName: 'Deshmukh',
    fullName: 'Neha Deshmukh',
    email: 'neha.deshmukh@arqensial.com',
    phone: '+91 98202 23456',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    role: 'manager',
    departmentId: 'dept-dev',
    departmentName: 'Development',
    designation: 'Operations Manager',
    reportingManagerId: 'emp-001',
    reportingManagerName: 'Sameer Kanojiya',
    employmentType: 'Full-Time',
    status: 'Active',
    joiningDate: '2023-02-01',
    location: 'Mumbai HQ',
    workShift: 'General Shift (09:30 - 18:30)',
    salaryStructure: {
      annualCTC: 2400000,
      monthlyGross: 200000,
      basic: 100000,
      hra: 40000,
      specialAllowance: 58000,
      conveyance: 2000,
      performanceBonus: 0,
      pfEmployee: 1800,
      pfEmployer: 1800,
      esi: 0,
      professionalTax: 200,
      tdsMonthly: 26000,
      netMonthly: 172000,
    },
    bankDetails: {
      accountHolder: 'Neha Deshmukh',
      bankName: 'ICICI Bank Ltd',
      accountNumber: '••••••••7731',
      ifscSwift: 'ICIC0000045',
      branch: 'Andheri East, Mumbai',
      panNumber: 'BBMND4821K',
      uanNumber: '10148822002',
    },
    emergencyContacts: [{ name: 'Sunil Deshmukh', relation: 'Father', phone: '+91 98202 88888' }],
    documents: [],
    skills: ['Agile Project Management', 'Sprint Planning', 'Delivery Excellence', 'Team Leadership'],
    experience: [],
    education: [{ degree: 'MBA Operations', institution: 'NMIMS Mumbai', year: '2016', grade: 'First Class' }],
    notes: [],
  },
  {
    id: 'emp-003',
    tenantId: TENANT_ID,
    empCode: 'AT-1003',
    firstName: 'Rahul',
    lastName: 'Mehta',
    fullName: 'Rahul Mehta',
    email: 'rahul.mehta@arqensial.com',
    phone: '+91 98203 34567',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    role: 'team_leader',
    departmentId: 'dept-dev',
    departmentName: 'Development',
    designation: 'Senior Team Leader',
    reportingManagerId: 'emp-002',
    reportingManagerName: 'Neha Deshmukh',
    employmentType: 'Full-Time',
    status: 'Active',
    joiningDate: '2023-03-15',
    location: 'Mumbai HQ',
    workShift: 'General Shift (09:30 - 18:30)',
    salaryStructure: {
      annualCTC: 1800000,
      monthlyGross: 150000,
      basic: 75000,
      hra: 30000,
      specialAllowance: 43000,
      conveyance: 2000,
      performanceBonus: 0,
      pfEmployee: 1800,
      pfEmployer: 1800,
      esi: 0,
      professionalTax: 200,
      tdsMonthly: 16000,
      netMonthly: 132000,
    },
    bankDetails: {
      accountHolder: 'Rahul Mehta',
      bankName: 'State Bank of India',
      accountNumber: '••••••••9012',
      ifscSwift: 'SBIN0001822',
      branch: 'Borivali West, Mumbai',
      panNumber: 'CCPRM8392L',
      uanNumber: '10148822003',
    },
    emergencyContacts: [{ name: 'Anita Mehta', relation: 'Mother', phone: '+91 98203 77777' }],
    documents: [],
    skills: ['Full Stack Architecture', 'Node.js', 'React', 'PostgreSQL', 'System Design'],
    experience: [],
    education: [],
    notes: [],
  },
  {
    id: 'emp-004',
    tenantId: TENANT_ID,
    empCode: 'AT-1004',
    firstName: 'Priya',
    lastName: 'Kulkarni',
    fullName: 'Priya Kulkarni',
    email: 'priya.kulkarni@arqensial.com',
    phone: '+91 98204 45678',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    role: 'team_leader',
    departmentId: 'dept-seo',
    departmentName: 'SEO',
    designation: 'Senior Team Leader',
    reportingManagerId: 'emp-002',
    reportingManagerName: 'Neha Deshmukh',
    employmentType: 'Full-Time',
    status: 'Active',
    joiningDate: '2023-04-01',
    location: 'Mumbai HQ',
    workShift: 'General Shift (09:30 - 18:30)',
    salaryStructure: {
      annualCTC: 1650000,
      monthlyGross: 137500,
      basic: 68750,
      hra: 27500,
      specialAllowance: 39250,
      conveyance: 2000,
      performanceBonus: 0,
      pfEmployee: 1800,
      pfEmployer: 1800,
      esi: 0,
      professionalTax: 200,
      tdsMonthly: 13500,
      netMonthly: 122000,
    },
    bankDetails: {
      accountHolder: 'Priya Kulkarni',
      bankName: 'Axis Bank Ltd',
      accountNumber: '••••••••3421',
      ifscSwift: 'UTIB0000213',
      branch: 'Malad Link Road, Mumbai',
      panNumber: 'DDAPK9102P',
      uanNumber: '10148822004',
    },
    emergencyContacts: [],
    documents: [],
    skills: ['Enterprise SEO', 'Technical Audits', 'Ahrefs & SEMrush', 'Core Web Vitals'],
    experience: [],
    education: [],
    notes: [],
  },
  {
    id: 'emp-005',
    tenantId: TENANT_ID,
    empCode: 'AT-1005',
    firstName: 'Kunal',
    lastName: 'Joshi',
    fullName: 'Kunal Joshi',
    email: 'kunal.joshi@arqensial.com',
    phone: '+91 98205 56789',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    role: 'team_leader',
    departmentId: 'dept-uiux',
    departmentName: 'UI/UX',
    designation: 'Team Leader',
    reportingManagerId: 'emp-002',
    reportingManagerName: 'Neha Deshmukh',
    employmentType: 'Full-Time',
    status: 'Active',
    joiningDate: '2023-05-10',
    location: 'Mumbai HQ',
    workShift: 'General Shift (09:30 - 18:30)',
    salaryStructure: {
      annualCTC: 1400000,
      monthlyGross: 116666,
      basic: 58333,
      hra: 23333,
      specialAllowance: 33000,
      conveyance: 2000,
      performanceBonus: 0,
      pfEmployee: 1800,
      pfEmployer: 1800,
      esi: 0,
      professionalTax: 200,
      tdsMonthly: 9666,
      netMonthly: 105000,
    },
    bankDetails: {
      accountHolder: 'Kunal Joshi',
      bankName: 'Kotak Mahindra Bank',
      accountNumber: '••••••••6643',
      ifscSwift: 'KKBK0000671',
      branch: 'Kandivali West, Mumbai',
      panNumber: 'EEPKJ1982Q',
      uanNumber: '10148822005',
    },
    emergencyContacts: [],
    documents: [],
    skills: ['Figma Design Systems', 'User Research', 'Wireframing', 'Prototyping', 'WCAG AA'],
    experience: [],
    education: [],
    notes: [],
  },
  {
    id: 'emp-006',
    tenantId: TENANT_ID,
    empCode: 'AT-1006',
    firstName: 'Aditya',
    lastName: 'Patil',
    fullName: 'Aditya Patil',
    email: 'aditya.patil@arqensial.com',
    phone: '+91 98206 67890',
    avatarUrl: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=150&auto=format&fit=crop&q=80',
    role: 'team_leader',
    departmentId: 'dept-dev',
    departmentName: 'Development',
    designation: 'Team Leader',
    reportingManagerId: 'emp-003',
    reportingManagerName: 'Rahul Mehta',
    employmentType: 'Full-Time',
    status: 'Active',
    joiningDate: '2023-06-01',
    location: 'Mira Road Office',
    workShift: 'General Shift (09:30 - 18:30)',
    salaryStructure: {
      annualCTC: 1350000,
      monthlyGross: 112500,
      basic: 56250,
      hra: 22500,
      specialAllowance: 31750,
      conveyance: 2000,
      performanceBonus: 0,
      pfEmployee: 1800,
      pfEmployer: 1800,
      esi: 0,
      professionalTax: 200,
      tdsMonthly: 9000,
      netMonthly: 101500,
    },
    bankDetails: {
      accountHolder: 'Aditya Patil',
      bankName: 'HDFC Bank Ltd',
      accountNumber: '••••••••1928',
      ifscSwift: 'HDFC0001021',
      branch: 'Mira Road East Branch, Thane',
      panNumber: 'FFPAP3821R',
      uanNumber: '10148822006',
    },
    emergencyContacts: [],
    documents: [],
    skills: ['React Native', 'Frontend Architecture', 'TypeScript', 'REST APIs', 'Code Reviews'],
    experience: [],
    education: [],
    notes: [],
  },
  {
    id: 'emp-007',
    tenantId: TENANT_ID,
    empCode: 'AT-1007',
    firstName: 'Sneha',
    lastName: 'Nair',
    fullName: 'Sneha Nair',
    email: 'sneha.nair@arqensial.com',
    phone: '+91 98207 78901',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    role: 'team_leader',
    departmentId: 'dept-sls',
    departmentName: 'Sales',
    designation: 'Team Leader',
    reportingManagerId: 'emp-002',
    reportingManagerName: 'Neha Deshmukh',
    employmentType: 'Full-Time',
    status: 'Active',
    joiningDate: '2023-06-15',
    location: 'Mumbai HQ',
    workShift: 'General Shift (09:30 - 18:30)',
    salaryStructure: {
      annualCTC: 1300000,
      monthlyGross: 108333,
      basic: 54166,
      hra: 21666,
      specialAllowance: 30501,
      conveyance: 2000,
      performanceBonus: 0,
      pfEmployee: 1800,
      pfEmployer: 1800,
      esi: 0,
      professionalTax: 200,
      tdsMonthly: 8333,
      netMonthly: 98000,
    },
    bankDetails: {
      accountHolder: 'Sneha Nair',
      bankName: 'ICICI Bank Ltd',
      accountNumber: '••••••••5512',
      ifscSwift: 'ICIC0000109',
      branch: 'Goregaon West, Mumbai',
      panNumber: 'GGSNA8912S',
      uanNumber: '10148822007',
    },
    emergencyContacts: [],
    documents: [],
    skills: ['B2B SaaS Sales', 'Client Pipeline', 'Contract Negotiation', 'Account Management'],
    experience: [],
    education: [],
    notes: [],
  },
  {
    id: 'emp-008',
    tenantId: TENANT_ID,
    empCode: 'AT-1008',
    firstName: 'Rajesh',
    lastName: 'Gupta',
    fullName: 'Rajesh Gupta',
    email: 'rajesh.gupta@arqensial.com',
    phone: '+91 98208 89012',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    role: 'payroll_manager',
    departmentId: 'dept-acc',
    departmentName: 'Accounts',
    designation: 'Operations Manager',
    reportingManagerId: 'emp-002',
    reportingManagerName: 'Neha Deshmukh',
    employmentType: 'Full-Time',
    status: 'Active',
    joiningDate: '2023-07-01',
    location: 'Mumbai HQ',
    workShift: 'General Shift (09:30 - 18:30)',
    salaryStructure: {
      annualCTC: 1600000,
      monthlyGross: 133333,
      basic: 66666,
      hra: 26666,
      specialAllowance: 38001,
      conveyance: 2000,
      performanceBonus: 0,
      pfEmployee: 1800,
      pfEmployer: 1800,
      esi: 0,
      professionalTax: 200,
      tdsMonthly: 13333,
      netMonthly: 118000,
    },
    bankDetails: {
      accountHolder: 'Rajesh Gupta',
      bankName: 'State Bank of India',
      accountNumber: '••••••••8819',
      ifscSwift: 'SBIN0000412',
      branch: 'Nariman Point, Mumbai',
      panNumber: 'HHRGP4910T',
      uanNumber: '10148822008',
    },
    emergencyContacts: [],
    documents: [],
    skills: ['Indian Corporate Taxation', 'PF & ESI ECR Generation', 'TDS Filing', 'Tally & Zoho Books'],
    experience: [],
    education: [{ degree: 'CA Inter / M.Com', institution: 'Mumbai University', year: '2015', grade: 'First Class' }],
    notes: [],
  },
  {
    id: 'emp-009',
    tenantId: TENANT_ID,
    empCode: 'AT-1009',
    firstName: 'Ananya',
    lastName: 'Iyer',
    fullName: 'Ananya Iyer',
    email: 'ananya.iyer@arqensial.com',
    phone: '+91 98209 90123',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    role: 'hr_manager',
    departmentId: 'dept-hr',
    departmentName: 'HR',
    designation: 'HR Executive',
    reportingManagerId: 'emp-001',
    reportingManagerName: 'Sameer Kanojiya',
    employmentType: 'Full-Time',
    status: 'Active',
    joiningDate: '2023-07-15',
    location: 'Mumbai HQ',
    workShift: 'General Shift (09:30 - 18:30)',
    salaryStructure: {
      annualCTC: 900000,
      monthlyGross: 75000,
      basic: 37500,
      hra: 15000,
      specialAllowance: 20500,
      conveyance: 2000,
      performanceBonus: 0,
      pfEmployee: 1800,
      pfEmployer: 1800,
      esi: 0,
      professionalTax: 200,
      tdsMonthly: 4000,
      netMonthly: 69000,
    },
    bankDetails: {
      accountHolder: 'Ananya Iyer',
      bankName: 'HDFC Bank Ltd',
      accountNumber: '••••••••2231',
      ifscSwift: 'HDFC0000240',
      branch: 'Matunga East, Mumbai',
      panNumber: 'IIAIY7381U',
      uanNumber: '10148822009',
    },
    emergencyContacts: [],
    documents: [],
    skills: ['Employee Relations', 'Talent Sourcing', 'HR Compliance', 'Onboarding & Exits'],
    experience: [],
    education: [{ degree: 'MBA Human Resources', institution: 'Welingkar Institute Mumbai', year: '2019', grade: 'A' }],
    notes: [],
  },
  {
    id: 'emp-010',
    tenantId: TENANT_ID,
    empCode: 'AT-1010',
    firstName: 'Pooja',
    lastName: 'Shah',
    fullName: 'Pooja Shah',
    email: 'pooja.shah@arqensial.com',
    phone: '+91 98210 01234',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    role: 'employee',
    departmentId: 'dept-hr',
    departmentName: 'HR',
    designation: 'HR Executive',
    reportingManagerId: 'emp-009',
    reportingManagerName: 'Ananya Iyer',
    employmentType: 'Full-Time',
    status: 'Active',
    joiningDate: '2023-08-01',
    location: 'Mira Road Office',
    workShift: 'General Shift (09:30 - 18:30)',
    salaryStructure: {
      annualCTC: 650000,
      monthlyGross: 54166,
      basic: 27083,
      hra: 10833,
      specialAllowance: 14250,
      conveyance: 2000,
      performanceBonus: 0,
      pfEmployee: 1800,
      pfEmployer: 1800,
      esi: 0,
      professionalTax: 200,
      tdsMonthly: 1500,
      netMonthly: 50666,
    },
    bankDetails: {
      accountHolder: 'Pooja Shah',
      bankName: 'Axis Bank Ltd',
      accountNumber: '••••••••9941',
      ifscSwift: 'UTIB0001099',
      branch: 'Mira Road Station, Thane',
      panNumber: 'JJPSH9102V',
      uanNumber: '10148822010',
    },
    emergencyContacts: [],
    documents: [],
    skills: ['Leave Attendance Coordination', 'Campus Hiring', 'Event Management', 'Employee Engagement'],
    experience: [],
    education: [],
    notes: [],
  },
  {
    id: 'emp-011',
    tenantId: TENANT_ID,
    empCode: 'AT-1011',
    firstName: 'Vikram',
    lastName: 'Shinde',
    fullName: 'Vikram Shinde',
    email: 'vikram.shinde@arqensial.com',
    phone: '+91 98211 12345',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    role: 'employee',
    departmentId: 'dept-dev',
    departmentName: 'Development',
    designation: 'Web Developer',
    reportingManagerId: 'emp-003',
    reportingManagerName: 'Rahul Mehta',
    employmentType: 'Full-Time',
    status: 'Active',
    joiningDate: '2023-08-15',
    location: 'Mumbai HQ',
    workShift: 'General Shift (09:30 - 18:30)',
    salaryStructure: {
      annualCTC: 1050000,
      monthlyGross: 87500,
      basic: 43750,
      hra: 17500,
      specialAllowance: 24250,
      conveyance: 2000,
      performanceBonus: 0,
      pfEmployee: 1800,
      pfEmployer: 1800,
      esi: 0,
      professionalTax: 200,
      tdsMonthly: 5500,
      netMonthly: 80000,
    },
    bankDetails: {
      accountHolder: 'Vikram Shinde',
      bankName: 'Kotak Mahindra Bank',
      accountNumber: '••••••••4810',
      ifscSwift: 'KKBK0000188',
      branch: 'Dadar West, Mumbai',
      panNumber: 'KKVSH8210W',
      uanNumber: '10148822011',
    },
    emergencyContacts: [],
    documents: [],
    skills: ['React', 'Next.js', 'Tailwind CSS', 'Redux Toolkit', 'TypeScript'],
    experience: [],
    education: [],
    notes: [],
  },
  {
    id: 'emp-012',
    tenantId: TENANT_ID,
    empCode: 'AT-1012',
    firstName: 'Siddharth',
    lastName: 'Rao',
    fullName: 'Siddharth Rao',
    email: 'siddharth.rao@arqensial.com',
    phone: '+91 98212 23456',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    role: 'employee',
    departmentId: 'dept-dev',
    departmentName: 'Development',
    designation: 'Web Developer',
    reportingManagerId: 'emp-006',
    reportingManagerName: 'Aditya Patil',
    employmentType: 'Full-Time',
    status: 'Active',
    joiningDate: '2023-09-01',
    location: 'Mumbai HQ',
    workShift: 'General Shift (09:30 - 18:30)',
    salaryStructure: {
      annualCTC: 950000,
      monthlyGross: 79166,
      basic: 39583,
      hra: 15833,
      specialAllowance: 21750,
      conveyance: 2000,
      performanceBonus: 0,
      pfEmployee: 1800,
      pfEmployer: 1800,
      esi: 0,
      professionalTax: 200,
      tdsMonthly: 4500,
      netMonthly: 72666,
    },
    bankDetails: {
      accountHolder: 'Siddharth Rao',
      bankName: 'HDFC Bank Ltd',
      accountNumber: '••••••••8192',
      ifscSwift: 'HDFC0000092',
      branch: 'Bandra West, Mumbai',
      panNumber: 'LLSRA3918X',
      uanNumber: '10148822012',
    },
    emergencyContacts: [],
    documents: [],
    skills: ['Node.js', 'Express', 'PostgreSQL', 'Prisma ORM', 'Redis'],
    experience: [],
    education: [],
    notes: [],
  },
  {
    id: 'emp-013',
    tenantId: TENANT_ID,
    empCode: 'AT-1013',
    firstName: 'Tanvi',
    lastName: 'Sawant',
    fullName: 'Tanvi Sawant',
    email: 'tanvi.sawant@arqensial.com',
    phone: '+91 98213 34567',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    role: 'employee',
    departmentId: 'dept-dev',
    departmentName: 'Development',
    designation: 'Web Developer',
    reportingManagerId: 'emp-006',
    reportingManagerName: 'Aditya Patil',
    employmentType: 'Full-Time',
    status: 'Active',
    joiningDate: '2023-09-15',
    location: 'Mira Road Office',
    workShift: 'General Shift (09:30 - 18:30)',
    salaryStructure: {
      annualCTC: 850000,
      monthlyGross: 70833,
      basic: 35416,
      hra: 14166,
      specialAllowance: 19251,
      conveyance: 2000,
      performanceBonus: 0,
      pfEmployee: 1800,
      pfEmployer: 1800,
      esi: 0,
      professionalTax: 200,
      tdsMonthly: 3500,
      netMonthly: 65333,
    },
    bankDetails: {
      accountHolder: 'Tanvi Sawant',
      bankName: 'Bank of Baroda',
      accountNumber: '••••••••3319',
      ifscSwift: 'BARB0BHAYAN',
      branch: 'Bhayander West, Thane',
      panNumber: 'MMTSA9102Y',
      uanNumber: '10148822013',
    },
    emergencyContacts: [],
    documents: [],
    skills: ['Frontend Development', 'Vue.js', 'React', 'CSS Grid', 'REST Integration'],
    experience: [],
    education: [],
    notes: [],
  },
  {
    id: 'emp-014',
    tenantId: TENANT_ID,
    empCode: 'AT-1014',
    firstName: 'Amit',
    lastName: 'Chaurasia',
    fullName: 'Amit Chaurasia',
    email: 'amit.chaurasia@arqensial.com',
    phone: '+91 98214 45678',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    role: 'employee',
    departmentId: 'dept-dev',
    departmentName: 'Development',
    designation: 'Web Developer',
    reportingManagerId: 'emp-006',
    reportingManagerName: 'Aditya Patil',
    employmentType: 'Full-Time',
    status: 'Active',
    joiningDate: '2023-10-01',
    location: 'Mira Road Office',
    workShift: 'General Shift (09:30 - 18:30)',
    salaryStructure: {
      annualCTC: 800000,
      monthlyGross: 66666,
      basic: 33333,
      hra: 13333,
      specialAllowance: 18000,
      conveyance: 2000,
      performanceBonus: 0,
      pfEmployee: 1800,
      pfEmployer: 1800,
      esi: 0,
      professionalTax: 200,
      tdsMonthly: 3000,
      netMonthly: 61666,
    },
    bankDetails: {
      accountHolder: 'Amit Chaurasia',
      bankName: 'State Bank of India',
      accountNumber: '••••••••6021',
      ifscSwift: 'SBIN0005121',
      branch: 'Thane West Station',
      panNumber: 'NNACH8192Z',
      uanNumber: '10148822014',
    },
    emergencyContacts: [],
    documents: [],
    skills: ['Python', 'FastAPI', 'MongoDB', 'Docker', 'Git Workflows'],
    experience: [],
    education: [],
    notes: [],
  },
  {
    id: 'emp-015',
    tenantId: TENANT_ID,
    empCode: 'AT-1015',
    firstName: 'Manish',
    lastName: 'Tiwari',
    fullName: 'Manish Tiwari',
    email: 'manish.tiwari@arqensial.com',
    phone: '+91 98215 56789',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    role: 'employee',
    departmentId: 'dept-dev',
    departmentName: 'Development',
    designation: 'Web Developer',
    reportingManagerId: 'emp-003',
    reportingManagerName: 'Rahul Mehta',
    employmentType: 'Full-Time',
    status: 'Active',
    joiningDate: '2023-10-15',
    location: 'Mumbai HQ',
    workShift: 'General Shift (09:30 - 18:30)',
    salaryStructure: {
      annualCTC: 900000,
      monthlyGross: 75000,
      basic: 37500,
      hra: 15000,
      specialAllowance: 20500,
      conveyance: 2000,
      performanceBonus: 0,
      pfEmployee: 1800,
      pfEmployer: 1800,
      esi: 0,
      professionalTax: 200,
      tdsMonthly: 4000,
      netMonthly: 69000,
    },
    bankDetails: {
      accountHolder: 'Manish Tiwari',
      bankName: 'HDFC Bank Ltd',
      accountNumber: '••••••••4412',
      ifscSwift: 'HDFC0000182',
      branch: 'Kurla West, Mumbai',
      panNumber: 'OOPMT1029A',
      uanNumber: '10148822015',
    },
    emergencyContacts: [],
    documents: [],
    skills: ['Full Stack Dev', 'React 19', 'GraphQL', 'PostgreSQL', 'Tailwind'],
    experience: [],
    education: [],
    notes: [],
  },
  {
    id: 'emp-016',
    tenantId: TENANT_ID,
    empCode: 'AT-1016',
    firstName: 'Riya',
    lastName: 'Sen',
    fullName: 'Riya Sen',
    email: 'riya.sen@arqensial.com',
    phone: '+91 98216 67890',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    role: 'employee',
    departmentId: 'dept-uiux',
    departmentName: 'UI/UX',
    designation: 'UI Designer',
    reportingManagerId: 'emp-005',
    reportingManagerName: 'Kunal Joshi',
    employmentType: 'Full-Time',
    status: 'Active',
    joiningDate: '2023-11-01',
    location: 'Mumbai HQ',
    workShift: 'General Shift (09:30 - 18:30)',
    salaryStructure: {
      annualCTC: 850000,
      monthlyGross: 70833,
      basic: 35416,
      hra: 14166,
      specialAllowance: 19251,
      conveyance: 2000,
      performanceBonus: 0,
      pfEmployee: 1800,
      pfEmployer: 1800,
      esi: 0,
      professionalTax: 200,
      tdsMonthly: 3500,
      netMonthly: 65333,
    },
    bankDetails: {
      accountHolder: 'Riya Sen',
      bankName: 'Axis Bank Ltd',
      accountNumber: '••••••••1184',
      ifscSwift: 'UTIB0000055',
      branch: 'Vile Parle East, Mumbai',
      panNumber: 'PPRSE8192B',
      uanNumber: '10148822016',
    },
    emergencyContacts: [],
    documents: [],
    skills: ['Figma', 'Adobe XD', 'Micro-interactions', 'Design Tokens', 'Prototyping'],
    experience: [],
    education: [],
    notes: [],
  },
  {
    id: 'emp-017',
    tenantId: TENANT_ID,
    empCode: 'AT-1017',
    firstName: 'Farhan',
    lastName: 'Khan',
    fullName: 'Farhan Khan',
    email: 'farhan.khan@arqensial.com',
    phone: '+91 98217 78901',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    role: 'employee',
    departmentId: 'dept-uiux',
    departmentName: 'UI/UX',
    designation: 'UI Designer',
    reportingManagerId: 'emp-005',
    reportingManagerName: 'Kunal Joshi',
    employmentType: 'Full-Time',
    status: 'Active',
    joiningDate: '2023-11-15',
    location: 'Mira Road Office',
    workShift: 'General Shift (09:30 - 18:30)',
    salaryStructure: {
      annualCTC: 780000,
      monthlyGross: 65000,
      basic: 32500,
      hra: 13000,
      specialAllowance: 17500,
      conveyance: 2000,
      performanceBonus: 0,
      pfEmployee: 1800,
      pfEmployer: 1800,
      esi: 0,
      professionalTax: 200,
      tdsMonthly: 2800,
      netMonthly: 60200,
    },
    bankDetails: {
      accountHolder: 'Farhan Khan',
      bankName: 'ICICI Bank Ltd',
      accountNumber: '••••••••7719',
      ifscSwift: 'ICIC0000881',
      branch: 'Mira Bhayander Road, Thane',
      panNumber: 'QQFKH9102C',
      uanNumber: '10148822017',
    },
    emergencyContacts: [],
    documents: [],
    skills: ['Mobile App UI', 'Responsive Web Layouts', 'Iconography', 'Illustrations'],
    experience: [],
    education: [],
    notes: [],
  },
  {
    id: 'emp-018',
    tenantId: TENANT_ID,
    empCode: 'AT-1018',
    firstName: 'Nikhil',
    lastName: 'Gawde',
    fullName: 'Nikhil Gawde',
    email: 'nikhil.gawde@arqensial.com',
    phone: '+91 98218 89012',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    role: 'employee',
    departmentId: 'dept-seo',
    departmentName: 'SEO',
    designation: 'SEO Executive',
    reportingManagerId: 'emp-004',
    reportingManagerName: 'Priya Kulkarni',
    employmentType: 'Full-Time',
    status: 'Active',
    joiningDate: '2023-12-01',
    location: 'Mumbai HQ',
    workShift: 'General Shift (09:30 - 18:30)',
    salaryStructure: {
      annualCTC: 720000,
      monthlyGross: 60000,
      basic: 30000,
      hra: 12000,
      specialAllowance: 16000,
      conveyance: 2000,
      performanceBonus: 0,
      pfEmployee: 1800,
      pfEmployer: 1800,
      esi: 0,
      professionalTax: 200,
      tdsMonthly: 2200,
      netMonthly: 55800,
    },
    bankDetails: {
      accountHolder: 'Nikhil Gawde',
      bankName: 'State Bank of India',
      accountNumber: '••••••••4819',
      ifscSwift: 'SBIN0000189',
      branch: 'Goregaon East, Mumbai',
      panNumber: 'RRNGA4821D',
      uanNumber: '10148822018',
    },
    emergencyContacts: [],
    documents: [],
    skills: ['On-Page SEO', 'Keyword Research', 'Google Search Console', 'Screaming Frog'],
    experience: [],
    education: [],
    notes: [],
  },
  {
    id: 'emp-019',
    tenantId: TENANT_ID,
    empCode: 'AT-1019',
    firstName: 'Meera',
    lastName: 'Nambiar',
    fullName: 'Meera Nambiar',
    email: 'meera.nambiar@arqensial.com',
    phone: '+91 98219 90123',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    role: 'employee',
    departmentId: 'dept-seo',
    departmentName: 'SEO',
    designation: 'SEO Executive',
    reportingManagerId: 'emp-004',
    reportingManagerName: 'Priya Kulkarni',
    employmentType: 'Full-Time',
    status: 'Active',
    joiningDate: '2024-01-10',
    location: 'Mira Road Office',
    workShift: 'General Shift (09:30 - 18:30)',
    salaryStructure: {
      annualCTC: 660000,
      monthlyGross: 55000,
      basic: 27500,
      hra: 11000,
      specialAllowance: 14500,
      conveyance: 2000,
      performanceBonus: 0,
      pfEmployee: 1800,
      pfEmployer: 1800,
      esi: 0,
      professionalTax: 200,
      tdsMonthly: 1600,
      netMonthly: 51400,
    },
    bankDetails: {
      accountHolder: 'Meera Nambiar',
      bankName: 'HDFC Bank Ltd',
      accountNumber: '••••••••9810',
      ifscSwift: 'HDFC0000411',
      branch: 'Mira Road West, Thane',
      panNumber: 'SSMNA8192E',
      uanNumber: '10148822019',
    },
    emergencyContacts: [],
    documents: [],
    skills: ['Off-Page SEO', 'Backlink Building', 'Competitor Analysis', 'Content Optimization'],
    experience: [],
    education: [],
    notes: [],
  },
  {
    id: 'emp-020',
    tenantId: TENANT_ID,
    empCode: 'AT-1020',
    firstName: 'Gaurav',
    lastName: 'Mishra',
    fullName: 'Gaurav Mishra',
    email: 'gaurav.mishra@arqensial.com',
    phone: '+91 98220 01234',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    role: 'team_leader',
    departmentId: 'dept-mkt',
    departmentName: 'Digital Marketing',
    designation: 'Team Leader',
    reportingManagerId: 'emp-002',
    reportingManagerName: 'Neha Deshmukh',
    employmentType: 'Full-Time',
    status: 'Active',
    joiningDate: '2024-02-01',
    location: 'Mumbai HQ',
    workShift: 'General Shift (09:30 - 18:30)',
    salaryStructure: {
      annualCTC: 1200000,
      monthlyGross: 100000,
      basic: 50000,
      hra: 20000,
      specialAllowance: 28000,
      conveyance: 2000,
      performanceBonus: 0,
      pfEmployee: 1800,
      pfEmployer: 1800,
      esi: 0,
      professionalTax: 200,
      tdsMonthly: 7500,
      netMonthly: 90500,
    },
    bankDetails: {
      accountHolder: 'Gaurav Mishra',
      bankName: 'ICICI Bank Ltd',
      accountNumber: '••••••••6502',
      ifscSwift: 'ICIC0000199',
      branch: 'Oshiwara, Mumbai',
      panNumber: 'TTGMI9102F',
      uanNumber: '10148822020',
    },
    emergencyContacts: [],
    documents: [],
    skills: ['Performance Marketing', 'Google Ads', 'Meta Ad Manager', 'Analytics & Funnels'],
    experience: [],
    education: [],
    notes: [],
  },
  {
    id: 'emp-021',
    tenantId: TENANT_ID,
    empCode: 'AT-1021',
    firstName: 'Shweta',
    lastName: 'Pandey',
    fullName: 'Shweta Pandey',
    email: 'shweta.pandey@arqensial.com',
    phone: '+91 98221 12345',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    role: 'employee',
    departmentId: 'dept-cnt',
    departmentName: 'Content',
    designation: 'Content Writer',
    reportingManagerId: 'emp-020',
    reportingManagerName: 'Gaurav Mishra',
    employmentType: 'Full-Time',
    status: 'Active',
    joiningDate: '2024-02-15',
    location: 'Mumbai HQ',
    workShift: 'General Shift (09:30 - 18:30)',
    salaryStructure: {
      annualCTC: 700000,
      monthlyGross: 58333,
      basic: 29166,
      hra: 11666,
      specialAllowance: 15501,
      conveyance: 2000,
      performanceBonus: 0,
      pfEmployee: 1800,
      pfEmployer: 1800,
      esi: 0,
      professionalTax: 200,
      tdsMonthly: 2000,
      netMonthly: 54333,
    },
    bankDetails: {
      accountHolder: 'Shweta Pandey',
      bankName: 'Axis Bank Ltd',
      accountNumber: '••••••••3810',
      ifscSwift: 'UTIB0000412',
      branch: 'Malad West, Mumbai',
      panNumber: 'UUSPA4821G',
      uanNumber: '10148822021',
    },
    emergencyContacts: [],
    documents: [],
    skills: ['B2B Tech Copywriting', 'SEO Articles', 'Case Studies', 'Landing Page Copy'],
    experience: [],
    education: [],
    notes: [],
  },
  {
    id: 'emp-022',
    tenantId: TENANT_ID,
    empCode: 'AT-1022',
    firstName: 'Rohan',
    lastName: 'Bhatia',
    fullName: 'Rohan Bhatia',
    email: 'rohan.bhatia@arqensial.com',
    phone: '+91 98222 23456',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    role: 'employee',
    departmentId: 'dept-cnt',
    departmentName: 'Content',
    designation: 'Content Writer',
    reportingManagerId: 'emp-020',
    reportingManagerName: 'Gaurav Mishra',
    employmentType: 'Full-Time',
    status: 'Active',
    joiningDate: '2024-03-01',
    location: 'Mira Road Office',
    workShift: 'General Shift (09:30 - 18:30)',
    salaryStructure: {
      annualCTC: 620000,
      monthlyGross: 51666,
      basic: 25833,
      hra: 10333,
      specialAllowance: 13500,
      conveyance: 2000,
      performanceBonus: 0,
      pfEmployee: 1800,
      pfEmployer: 1800,
      esi: 0,
      professionalTax: 200,
      tdsMonthly: 1200,
      netMonthly: 48466,
    },
    bankDetails: {
      accountHolder: 'Rohan Bhatia',
      bankName: 'State Bank of India',
      accountNumber: '••••••••7739',
      ifscSwift: 'SBIN0000881',
      branch: 'Mira Road, Thane',
      panNumber: 'VVRBH8192H',
      uanNumber: '10148822022',
    },
    emergencyContacts: [],
    documents: [],
    skills: ['Technical Documentation', 'Blog Writing', 'Social Media Copy', 'Proofreading'],
    experience: [],
    education: [],
    notes: [],
  },
  {
    id: 'emp-023',
    tenantId: TENANT_ID,
    empCode: 'AT-1023',
    firstName: 'Deepak',
    lastName: 'Rathod',
    fullName: 'Deepak Rathod',
    email: 'deepak.rathod@arqensial.com',
    phone: '+91 98223 34567',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    role: 'employee',
    departmentId: 'dept-sls',
    departmentName: 'Sales',
    designation: 'Sales Executive',
    reportingManagerId: 'emp-007',
    reportingManagerName: 'Sneha Nair',
    employmentType: 'Full-Time',
    status: 'Active',
    joiningDate: '2024-03-15',
    location: 'Mumbai HQ',
    workShift: 'General Shift (09:30 - 18:30)',
    salaryStructure: {
      annualCTC: 750000,
      monthlyGross: 62500,
      basic: 31250,
      hra: 12500,
      specialAllowance: 16750,
      conveyance: 2000,
      performanceBonus: 0,
      pfEmployee: 1800,
      pfEmployer: 1800,
      esi: 0,
      professionalTax: 200,
      tdsMonthly: 2500,
      netMonthly: 57750,
    },
    bankDetails: {
      accountHolder: 'Deepak Rathod',
      bankName: 'HDFC Bank Ltd',
      accountNumber: '••••••••1109',
      ifscSwift: 'HDFC0000192',
      branch: 'Jogeshwari West, Mumbai',
      panNumber: 'WWDRT4910I',
      uanNumber: '10148822023',
    },
    emergencyContacts: [],
    documents: [],
    skills: ['Cold Outreach', 'Client Discovery', 'Product Demos', 'HubSpot CRM'],
    experience: [],
    education: [],
    notes: [],
  },
  {
    id: 'emp-024',
    tenantId: TENANT_ID,
    empCode: 'AT-1024',
    firstName: 'Natasha',
    lastName: "D'Souza",
    fullName: "Natasha D'Souza",
    email: 'natasha.dsouza@arqensial.com',
    phone: '+91 98224 45678',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    role: 'employee',
    departmentId: 'dept-sls',
    departmentName: 'Sales',
    designation: 'Sales Executive',
    reportingManagerId: 'emp-007',
    reportingManagerName: 'Sneha Nair',
    employmentType: 'Full-Time',
    status: 'Active',
    joiningDate: '2024-04-01',
    location: 'Mira Road Office',
    workShift: 'General Shift (09:30 - 18:30)',
    salaryStructure: {
      annualCTC: 700000,
      monthlyGross: 58333,
      basic: 29166,
      hra: 11666,
      specialAllowance: 15501,
      conveyance: 2000,
      performanceBonus: 0,
      pfEmployee: 1800,
      pfEmployer: 1800,
      esi: 0,
      professionalTax: 200,
      tdsMonthly: 2000,
      netMonthly: 54333,
    },
    bankDetails: {
      accountHolder: "Natasha D'Souza",
      bankName: 'Kotak Mahindra Bank',
      accountNumber: '••••••••4812',
      ifscSwift: 'KKBK0000812',
      branch: 'Mira Road East, Thane',
      panNumber: 'XXNDS9102J',
      uanNumber: '10148822024',
    },
    emergencyContacts: [],
    documents: [],
    skills: ['Lead Qualification', 'Customer Onboarding', 'Sales Presentations', 'Enterprise Follow-ups'],
    experience: [],
    education: [],
    notes: [],
  },
  {
    id: 'emp-025',
    tenantId: TENANT_ID,
    empCode: 'AT-1025',
    firstName: 'Kavita',
    lastName: 'Solanki',
    fullName: 'Kavita Solanki',
    email: 'kavita.solanki@arqensial.com',
    phone: '+91 98225 56789',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    role: 'employee',
    departmentId: 'dept-acc',
    departmentName: 'Accounts',
    designation: 'Operations Manager',
    reportingManagerId: 'emp-008',
    reportingManagerName: 'Rajesh Gupta',
    employmentType: 'Full-Time',
    status: 'Active',
    joiningDate: '2024-04-15',
    location: 'Mira Road Office',
    workShift: 'General Shift (09:30 - 18:30)',
    salaryStructure: {
      annualCTC: 1150000,
      monthlyGross: 95833,
      basic: 47916,
      hra: 19166,
      specialAllowance: 26751,
      conveyance: 2000,
      performanceBonus: 0,
      pfEmployee: 1800,
      pfEmployer: 1800,
      esi: 0,
      professionalTax: 200,
      tdsMonthly: 6800,
      netMonthly: 87033,
    },
    bankDetails: {
      accountHolder: 'Kavita Solanki',
      bankName: 'ICICI Bank Ltd',
      accountNumber: '••••••••9021',
      ifscSwift: 'ICIC0000411',
      branch: 'Bhayander East, Thane',
      panNumber: 'YYKSO8392K',
      uanNumber: '10148822025',
    },
    emergencyContacts: [],
    documents: [],
    skills: ['GST Returns', 'Bank Reconciliation', 'Vendor Invoicing', 'Financial Auditing'],
    experience: [],
    education: [{ degree: 'B.Com / Inter CA', institution: 'Mithibai College Mumbai', year: '2017', grade: 'First Class' }],
    notes: [],
  },
];
