import {
  Tenant,
  Department,
  Designation,
  BranchLocation,
  Shift,
  Holiday,
  Team,
  SubscriptionPlan,
  TenantCountryConfig,
  CompanyPayrollSettings,
} from '../../types';

export const TENANT_ARQENSIAL_ID = 'tenant-arqensial-01';
export const TENANT_NORTHSTAR_ID = 'tenant-northstar-02';
export const TENANT_VERTEX_ID = 'tenant-vertex-03';
export const TENANT_VASTRA_ID = 'tenant-vastra-vatika-04';

export const ARQENSIAL_COUNTRY_CONFIG: TenantCountryConfig = {
  tenantId: TENANT_ARQENSIAL_ID,
  countryCode: 'IN',
  legalCompanyName: 'Arqensial Technologies Private Limited',
  companyTaxId: '27AABCA1234F1Z5 / AABCA1234F',
  registrationNumber: 'U72900MH2022PTC123456',
  stateProvince: 'Maharashtra',
  city: 'Mumbai',
  financialYear: 'April - March',
  salaryCycle: 'Monthly',
  salaryPaymentDate: 1,
  weeklyWorkingDays: 5,
  weekendDays: ['Saturday', 'Sunday'],
  officialLanguage: 'English',
  dateFormat: 'DD/MM/YYYY',
  timeFormat: '12h',
  payrollEnabled: true,
  attendanceEnabled: true,
  leaveEnabled: true,
  statutoryComplianceEnabled: true,
  countrySpecificData: {
    pan: 'AABCA1234F',
    gstin: '27AABCA1234F1Z5',
    tan: 'MUMB12345F',
    pfEstablishmentCode: 'MH/BAN/0012345/000',
    esicCode: '31001234560001001',
    ptRegistrationNo: 'PT270112345',
  },
};

export const ARQENSIAL_PAYROLL_SETTINGS: CompanyPayrollSettings = {
  tenantId: TENANT_ARQENSIAL_ID,
  salaryCycle: 'Monthly',
  payrollCutOffDay: 25,
  salaryProcessingDay: 28,
  salaryPaymentDay: 1,
  attendanceLockDay: 26,
  leaveLockDay: 25,
  payrollDivisor: 'Calendar Days',
  gracePeriodMinutes: 15,
  lateMarkRule: {
    enabled: true,
    maxLateAllowedPerMonth: 3,
    actionAfterThreshold: 'Half Day LOP',
    lopDaysPerExcessLate: 0.5,
  },
  halfDayThresholdHours: 4.5,
  overtimeCalculationRule: {
    enabled: true,
    rateMultiplier: 1.5,
    minMinutesForOvertime: 60,
  },
  lopRule: {
    enabled: true,
    deductFromBasicOnly: false,
    deductFromGross: true,
  },
  weekendRule: {
    isPaid: true,
    requiresPresentAdjacent: false,
  },
  holidayRule: {
    isPaid: true,
  },
};

export const NORTHSTAR_COUNTRY_CONFIG: TenantCountryConfig = {
  tenantId: TENANT_NORTHSTAR_ID,
  countryCode: 'US',
  legalCompanyName: 'Northstar Digital Technologies Inc.',
  companyTaxId: 'EIN: 12-3456789',
  registrationNumber: 'DE-CORP-9876543',
  stateProvince: 'New York',
  city: 'New York City',
  financialYear: 'January - December',
  salaryCycle: 'Biweekly',
  salaryPaymentDate: 15,
  weeklyWorkingDays: 5,
  weekendDays: ['Saturday', 'Sunday'],
  officialLanguage: 'English (US)',
  dateFormat: 'MM/DD/YYYY',
  timeFormat: '12h',
  payrollEnabled: true,
  attendanceEnabled: true,
  leaveEnabled: true,
  statutoryComplianceEnabled: true,
  countrySpecificData: {
    ein: '12-3456789',
    stateWithholdingId: 'NYS-WH-449102',
    unemploymentRate: 2.1,
  },
};

export const NORTHSTAR_PAYROLL_SETTINGS: CompanyPayrollSettings = {
  tenantId: TENANT_NORTHSTAR_ID,
  salaryCycle: 'Biweekly',
  payrollCutOffDay: 12,
  salaryProcessingDay: 14,
  salaryPaymentDay: 15,
  attendanceLockDay: 13,
  leaveLockDay: 12,
  payrollDivisor: 'Working Days',
  gracePeriodMinutes: 10,
  lateMarkRule: {
    enabled: true,
    maxLateAllowedPerMonth: 2,
    actionAfterThreshold: 'Warning Only',
    lopDaysPerExcessLate: 0,
  },
  halfDayThresholdHours: 4.0,
  overtimeCalculationRule: {
    enabled: true,
    rateMultiplier: 1.5,
    minMinutesForOvertime: 40,
  },
  lopRule: {
    enabled: true,
    deductFromBasicOnly: false,
    deductFromGross: true,
  },
  weekendRule: {
    isPaid: false,
    requiresPresentAdjacent: false,
  },
  holidayRule: {
    isPaid: true,
  },
};

export const VERTEX_COUNTRY_CONFIG: TenantCountryConfig = {
  tenantId: TENANT_VERTEX_ID,
  countryCode: 'AE',
  legalCompanyName: 'Vertex Global Management Consulting LLC',
  companyTaxId: 'TRN: 100482910300003',
  registrationNumber: 'DED-CN-884920',
  stateProvince: 'Dubai',
  city: 'Dubai',
  financialYear: 'January - December',
  salaryCycle: 'Monthly',
  salaryPaymentDate: 28,
  weeklyWorkingDays: 5,
  weekendDays: ['Saturday', 'Sunday'],
  officialLanguage: 'English & Arabic',
  dateFormat: 'DD/MM/YYYY',
  timeFormat: '12h',
  payrollEnabled: true,
  attendanceEnabled: true,
  leaveEnabled: true,
  statutoryComplianceEnabled: true,
  countrySpecificData: {
    trn: '100482910300003',
    molEmployerCode: 'MOL-DXB-9921',
    wpsBankCode: 'ENBD-WPS-01',
  },
};

export const VERTEX_PAYROLL_SETTINGS: CompanyPayrollSettings = {
  tenantId: TENANT_VERTEX_ID,
  salaryCycle: 'Monthly',
  payrollCutOffDay: 24,
  salaryProcessingDay: 26,
  salaryPaymentDay: 28,
  attendanceLockDay: 25,
  leaveLockDay: 24,
  payrollDivisor: 'Fixed 30 Days',
  gracePeriodMinutes: 15,
  lateMarkRule: {
    enabled: true,
    maxLateAllowedPerMonth: 3,
    actionAfterThreshold: 'Half Day LOP',
    lopDaysPerExcessLate: 0.5,
  },
  halfDayThresholdHours: 4.0,
  overtimeCalculationRule: {
    enabled: true,
    rateMultiplier: 1.25,
    minMinutesForOvertime: 60,
  },
  lopRule: {
    enabled: true,
    deductFromBasicOnly: false,
    deductFromGross: true,
  },
  weekendRule: {
    isPaid: true,
    requiresPresentAdjacent: false,
  },
  holidayRule: {
    isPaid: true,
  },
};

export const PRODUCTION_INITIAL_TENANTS: Tenant[] = [
  {
    id: TENANT_ARQENSIAL_ID,
    name: 'Arqensial Technologies Pvt Ltd',
    slug: 'arqensial',
    domain: 'arqensial.com',
    logo: 'AQ',
    industry: 'Digital Solutions, Web Engineering & Marketing',
    planId: 'enterprise',
    planName: 'Enterprise Scale',
    employeeCount: 25,
    status: 'active',
    countryCode: 'IN',
    legalCompanyName: 'Arqensial Technologies Private Limited',
    companyTaxId: '27AABCA1234F1Z5',
    registrationNumber: 'U72900MH2022PTC123456',
    currency: 'INR',
    currencySymbol: '₹',
    timezone: 'Asia/Kolkata (IST)',
    address: 'Arqensial Tower, 5th Floor, BKC, Bandra East, Mumbai, Maharashtra 400051',
    contactEmail: 'contact@arqensial.com',
    contactPhone: '+91 22 6123 4500',
    mrr: 245000,
    createdAt: '2024-01-15T08:00:00Z',
    countryConfig: ARQENSIAL_COUNTRY_CONFIG,
    payrollSettings: ARQENSIAL_PAYROLL_SETTINGS,
    settings: {
      geoFencingEnabled: true,
      selfieAttendanceEnabled: true,
      ipRestrictionEnabled: true,
      twoFactorEnforced: true,
      allowedIps: ['182.72.138.42', '103.21.244.10', '115.112.245.18'],
      officeCoordinates: { lat: 19.0657, lng: 72.8687, radiusMeters: 500 },
    },
  },
  {
    id: TENANT_NORTHSTAR_ID,
    name: 'Northstar Digital Inc.',
    slug: 'northstar-digital',
    domain: 'northstardigital.io',
    logo: 'ND',
    industry: 'Cloud Infrastructure & Enterprise Systems',
    planId: 'managed',
    planName: 'Enterprise Managed Instance',
    employeeCount: 18,
    status: 'active',
    countryCode: 'US',
    legalCompanyName: 'Northstar Digital Technologies Inc.',
    companyTaxId: 'EIN: 12-3456789',
    registrationNumber: 'DE-CORP-9876543',
    currency: 'USD',
    currencySymbol: '$',
    timezone: 'America/New_York (EST)',
    address: 'One World Trade Center, Suite 4800, New York, NY 10007',
    contactEmail: 'people@northstardigital.io',
    contactPhone: '+1 (212) 555-0199',
    mrr: 18500,
    createdAt: '2024-03-01T09:00:00Z',
    countryConfig: NORTHSTAR_COUNTRY_CONFIG,
    payrollSettings: NORTHSTAR_PAYROLL_SETTINGS,
    settings: {
      geoFencingEnabled: true,
      selfieAttendanceEnabled: false,
      ipRestrictionEnabled: false,
      twoFactorEnforced: true,
      allowedIps: ['198.51.100.14', '198.51.100.15'],
      officeCoordinates: { lat: 40.7127, lng: -74.0134, radiusMeters: 400 },
    },
  },
  {
    id: TENANT_VERTEX_ID,
    name: 'Vertex Consulting LLC',
    slug: 'vertex-consulting',
    domain: 'vertexconsulting.ae',
    logo: 'VC',
    industry: 'Strategic Advisory & Operations Consulting',
    planId: 'enterprise',
    planName: 'Enterprise Scale',
    employeeCount: 14,
    status: 'active',
    countryCode: 'AE',
    legalCompanyName: 'Vertex Global Management Consulting LLC',
    companyTaxId: 'TRN: 100482910300003',
    registrationNumber: 'DED-CN-884920',
    currency: 'AED',
    currencySymbol: 'AED ',
    timezone: 'Asia/Dubai (GST)',
    address: 'Emaar Square, Building 4, Downtown Dubai, UAE',
    contactEmail: 'hr@vertexconsulting.ae',
    contactPhone: '+971 4 367 8900',
    mrr: 29400,
    createdAt: '2024-05-10T10:00:00Z',
    countryConfig: VERTEX_COUNTRY_CONFIG,
    payrollSettings: VERTEX_PAYROLL_SETTINGS,
    settings: {
      geoFencingEnabled: true,
      selfieAttendanceEnabled: true,
      ipRestrictionEnabled: true,
      twoFactorEnforced: true,
      allowedIps: ['185.120.40.12'],
      officeCoordinates: { lat: 25.1972, lng: 55.2744, radiusMeters: 300 },
    },
  },
  {
    id: TENANT_VASTRA_ID,
    name: 'Vastra Vatika',
    companyCode: 'VASTRA',
    slug: 'vastra-vatika',
    domain: 'vastravatika.com',
    logo: 'VV',
    industry: 'Clothing Store & Ethnic Fashion Retail',
    planId: 'managed',
    planName: 'Enterprise Managed Instance',
    employeeCount: 8,
    status: 'active',
    countryCode: 'IN',
    legalCompanyName: 'Vastra Vatika Apparels Private Limited',
    companyTaxId: '27AABCV8899F1Z2',
    registrationNumber: 'U18101MH2023PTC456789',
    currency: 'INR',
    currencySymbol: '₹',
    timezone: 'Asia/Kolkata (IST)',
    address: 'Shop No. 12-14, Heritage Silk Plaza, Linking Road, Bandra West, Mumbai, Maharashtra 400050',
    contactEmail: 'admin@vastravatika.com',
    contactPhone: '+91 98200 12345',
    mrr: 0,
    createdAt: '2024-06-01T09:00:00Z',
    settings: {
      attendanceEnabled: true,
      leaveEnabled: true,
      payrollEnabled: true,
      forcePasswordChangeOnFirstLogin: true,
      geoFencingEnabled: true,
      selfieAttendanceEnabled: true,
      ipRestrictionEnabled: false,
      twoFactorEnforced: false,
      allowedIps: ['115.112.245.18'],
      officeCoordinates: { lat: 19.0596, lng: 72.8295, radiusMeters: 350 },
    },
  },
];

export const PRODUCTION_BRANCHES: BranchLocation[] = [
  {
    id: 'branch-mumbai-hq',
    tenantId: TENANT_ARQENSIAL_ID,
    name: 'Mumbai HQ',
    code: 'MUM-HQ',
    address: 'Arqensial Tower, 5th Floor, BKC, Bandra East, Mumbai, Maharashtra 400051',
    city: 'Mumbai',
    country: 'India',
    geoRadiusMeters: 500,
    latitude: 19.0657,
    longitude: 72.8687,
    ipWhitelists: ['182.72.138.42', '103.21.244.10'],
    activeEmployees: 16,
  },
  {
    id: 'branch-mira-road',
    tenantId: TENANT_ARQENSIAL_ID,
    name: 'Mira Road Office',
    code: 'MIRA-BR',
    address: 'Silver Park Plaza, Sector 3, Mira Bhayandar Road, Mira Road East, Thane, Maharashtra 401107',
    city: 'Thane / Mumbai Suburban',
    country: 'India',
    geoRadiusMeters: 400,
    latitude: 19.2812,
    longitude: 72.8561,
    ipWhitelists: ['115.112.245.18'],
    activeEmployees: 9,
  },
  {
    id: 'branch-nyc-hq',
    tenantId: TENANT_NORTHSTAR_ID,
    name: 'New York HQ',
    code: 'NYC-HQ',
    address: 'One World Trade Center, Suite 4800, New York, NY 10007',
    city: 'New York',
    country: 'United States',
    geoRadiusMeters: 400,
    latitude: 40.7127,
    longitude: -74.0134,
    ipWhitelists: ['198.51.100.14'],
    activeEmployees: 18,
  },
  {
    id: 'branch-dubai-hq',
    tenantId: TENANT_VERTEX_ID,
    name: 'Dubai Downtown HQ',
    code: 'DXB-HQ',
    address: 'Emaar Square, Building 4, Downtown Dubai, UAE',
    city: 'Dubai',
    country: 'United Arab Emirates',
    geoRadiusMeters: 300,
    latitude: 25.1972,
    longitude: 55.2744,
    ipWhitelists: ['185.120.40.12'],
    activeEmployees: 14,
  },
  {
    id: 'branch-vv-bandra',
    tenantId: TENANT_VASTRA_ID,
    name: 'Bandra West Flagship Boutique',
    code: 'VV-MUM',
    address: 'Shop No. 12-14, Heritage Silk Plaza, Linking Road, Bandra West, Mumbai 400050',
    city: 'Mumbai',
    country: 'India',
    geoRadiusMeters: 350,
    latitude: 19.0596,
    longitude: 72.8295,
    ipWhitelists: ['115.112.245.18'],
    activeEmployees: 8,
  },
];

export const PRODUCTION_DEPARTMENTS: Department[] = [
  // Arqensial (India)
  { id: 'dept-dev', tenantId: TENANT_ARQENSIAL_ID, name: 'Development', code: 'DEV', headEmployeeId: 'emp-03', headEmployeeName: 'Vikram Malhotra', employeeCount: 6, annualBudget: 6500000, location: 'Mumbai HQ' },
  { id: 'dept-uiux', tenantId: TENANT_ARQENSIAL_ID, name: 'UI/UX', code: 'UIUX', headEmployeeId: 'emp-04', headEmployeeName: 'Sneha Kulkarni', employeeCount: 3, annualBudget: 3200000, location: 'Mumbai HQ' },
  { id: 'dept-seo', tenantId: TENANT_ARQENSIAL_ID, name: 'SEO', code: 'SEO', headEmployeeId: 'emp-05', headEmployeeName: 'Rohan Deshmukh', employeeCount: 3, annualBudget: 2800000, location: 'Mira Road Office' },
  { id: 'dept-mktg', tenantId: TENANT_ARQENSIAL_ID, name: 'Digital Marketing', code: 'MKTG', headEmployeeId: 'emp-15', headEmployeeName: 'Arjun Rampal', employeeCount: 2, annualBudget: 2600000, location: 'Mumbai HQ' },
  { id: 'dept-content', tenantId: TENANT_ARQENSIAL_ID, name: 'Content', code: 'CONT', headEmployeeId: 'emp-17', headEmployeeName: 'Rahul Mehta', employeeCount: 3, annualBudget: 2400000, location: 'Mumbai HQ' },
  { id: 'dept-hr', tenantId: TENANT_ARQENSIAL_ID, name: 'HR', code: 'HR', headEmployeeId: 'emp-06', headEmployeeName: 'Ananya Iyer', employeeCount: 2, annualBudget: 2200000, location: 'Mumbai HQ' },
  { id: 'dept-sales', tenantId: TENANT_ARQENSIAL_ID, name: 'Sales', code: 'SALES', headEmployeeId: 'emp-21', headEmployeeName: 'Siddharth Singhania', employeeCount: 3, annualBudget: 3500000, location: 'Mumbai HQ' },
  { id: 'dept-accounts', tenantId: TENANT_ARQENSIAL_ID, name: 'Accounts', code: 'ACCT', headEmployeeId: 'emp-24', headEmployeeName: 'Sunita Hegde', employeeCount: 3, annualBudget: 2900000, location: 'Mumbai HQ' },

  // Northstar (US)
  { id: 'dept-ns-eng', tenantId: TENANT_NORTHSTAR_ID, name: 'Engineering', code: 'ENG', headEmployeeId: 'emp-ns-01', headEmployeeName: 'David Miller', employeeCount: 10, annualBudget: 1800000, location: 'New York HQ' },
  { id: 'dept-ns-sales', tenantId: TENANT_NORTHSTAR_ID, name: 'Sales & Growth', code: 'SALES', headEmployeeId: 'emp-ns-02', headEmployeeName: 'Jennifer Hayes', employeeCount: 8, annualBudget: 1200000, location: 'New York HQ' },

  // Vertex (UAE)
  { id: 'dept-vx-advisory', tenantId: TENANT_VERTEX_ID, name: 'Management Advisory', code: 'ADV', headEmployeeId: 'emp-vx-01', headEmployeeName: 'Tariq Al-Mansoor', employeeCount: 8, annualBudget: 2200000, location: 'Dubai Downtown HQ' },
  { id: 'dept-vx-ops', tenantId: TENANT_VERTEX_ID, name: 'Client Operations', code: 'OPS', headEmployeeId: 'emp-vx-02', headEmployeeName: 'Fatima Zahra', employeeCount: 6, annualBudget: 1600000, location: 'Dubai Downtown HQ' },

  // Vastra Vatika (Clothing Store & Retail Fashion)
  { id: 'dept-vv-sales', tenantId: TENANT_VASTRA_ID, name: 'Store Floor & Sales', code: 'SF-SALES', headEmployeeName: 'Priya Sharma', employeeCount: 4, annualBudget: 2200000, location: 'Bandra West Flagship Boutique' },
  { id: 'dept-vv-billing', tenantId: TENANT_VASTRA_ID, name: 'Billing, POS & Cashier Desk', code: 'BIL-CSH', headEmployeeName: 'Kavita Joshi', employeeCount: 2, annualBudget: 900000, location: 'Bandra West Flagship Boutique' },
  { id: 'dept-vv-stock', tenantId: TENANT_VASTRA_ID, name: 'Inventory & Stock Management', code: 'INV-STK', headEmployeeName: 'Rohan Gaikwad', employeeCount: 2, annualBudget: 1100000, location: 'Bandra West Flagship Boutique' },
  { id: 'dept-vv-tailor', tenantId: TENANT_VASTRA_ID, name: 'Tailoring, Fitting & Alterations', code: 'TLR-FIT', headEmployeeName: 'Master Irfan Ansari', employeeCount: 3, annualBudget: 1400000, location: 'Bandra West Flagship Boutique' },
  { id: 'dept-vv-admin', tenantId: TENANT_VASTRA_ID, name: 'Store Operations & Accounts', code: 'STR-OPS', headEmployeeName: 'Priya Sharma', employeeCount: 1, annualBudget: 800000, location: 'Bandra West Flagship Boutique' },
];

export const PRODUCTION_DESIGNATIONS: Designation[] = [
  { id: 'desig-01', tenantId: TENANT_ARQENSIAL_ID, title: 'CEO', departmentId: 'dept-dev', departmentName: 'Development', level: 'L8 - Executive', minSalary: 3000000, maxSalary: 6000000 },
  { id: 'desig-02', tenantId: TENANT_ARQENSIAL_ID, title: 'Operations Manager', departmentId: 'dept-accounts', departmentName: 'Accounts', level: 'L6 - Management', minSalary: 1400000, maxSalary: 2400000 },
  { id: 'desig-03', tenantId: TENANT_ARQENSIAL_ID, title: 'Senior Team Leader', departmentId: 'dept-dev', departmentName: 'Development', level: 'L5 - Lead', minSalary: 1200000, maxSalary: 2000000 },
  { id: 'desig-04', tenantId: TENANT_ARQENSIAL_ID, title: 'Team Leader', departmentId: 'dept-uiux', departmentName: 'UI/UX', level: 'L4 - Lead', minSalary: 900000, maxSalary: 1600000 },
  { id: 'desig-05', tenantId: TENANT_ARQENSIAL_ID, title: 'Web Developer', departmentId: 'dept-dev', departmentName: 'Development', level: 'L3 - Senior', minSalary: 600000, maxSalary: 1200000 },
  { id: 'desig-06', tenantId: TENANT_ARQENSIAL_ID, title: 'UI Designer', departmentId: 'dept-uiux', departmentName: 'UI/UX', level: 'L3 - Mid', minSalary: 550000, maxSalary: 1100000 },
  { id: 'desig-07', tenantId: TENANT_ARQENSIAL_ID, title: 'SEO Executive', departmentId: 'dept-seo', departmentName: 'SEO', level: 'L2 - Executive', minSalary: 450000, maxSalary: 850000 },
  { id: 'desig-08', tenantId: TENANT_ARQENSIAL_ID, title: 'Content Writer', departmentId: 'dept-content', departmentName: 'Content', level: 'L2 - Executive', minSalary: 400000, maxSalary: 750000 },
  { id: 'desig-09', tenantId: TENANT_ARQENSIAL_ID, title: 'HR Executive', departmentId: 'dept-hr', departmentName: 'HR', level: 'L3 - Executive', minSalary: 500000, maxSalary: 900000 },
  { id: 'desig-10', tenantId: TENANT_ARQENSIAL_ID, title: 'Sales Executive', departmentId: 'dept-sales', departmentName: 'Sales', level: 'L3 - Executive', minSalary: 500000, maxSalary: 1000000 },
];

export const PRODUCTION_TEAMS: Team[] = [
  { id: 'team-01', tenantId: TENANT_ARQENSIAL_ID, departmentId: 'dept-dev', departmentName: 'Development', name: 'Web Engineering Squad', leadEmployeeId: 'emp-03', leadEmployeeName: 'Vikram Malhotra', memberCount: 6 },
  { id: 'team-02', tenantId: TENANT_ARQENSIAL_ID, departmentId: 'dept-uiux', departmentName: 'UI/UX', name: 'Product Experience Studio', leadEmployeeId: 'emp-04', leadEmployeeName: 'Sneha Kulkarni', memberCount: 3 },
  { id: 'team-03', tenantId: TENANT_ARQENSIAL_ID, departmentId: 'dept-seo', departmentName: 'SEO', name: 'Organic Growth & Search', leadEmployeeId: 'emp-05', leadEmployeeName: 'Rohan Deshmukh', memberCount: 3 },
  { id: 'team-04', tenantId: TENANT_ARQENSIAL_ID, departmentId: 'dept-mktg', departmentName: 'Digital Marketing', name: 'Performance Marketing & Ads', leadEmployeeId: 'emp-15', leadEmployeeName: 'Arjun Rampal', memberCount: 2 },
  { id: 'team-05', tenantId: TENANT_ARQENSIAL_ID, departmentId: 'dept-content', departmentName: 'Content', name: 'Editorial & Brand Storytelling', leadEmployeeId: 'emp-17', leadEmployeeName: 'Rahul Mehta', memberCount: 3 },
  { id: 'team-06', tenantId: TENANT_ARQENSIAL_ID, departmentId: 'dept-hr', departmentName: 'HR', name: 'People Operations & Culture', leadEmployeeId: 'emp-06', leadEmployeeName: 'Ananya Iyer', memberCount: 2 },
  { id: 'team-07', tenantId: TENANT_ARQENSIAL_ID, departmentId: 'dept-sales', departmentName: 'Sales', name: 'Client Acquisition & Growth', leadEmployeeId: 'emp-21', leadEmployeeName: 'Siddharth Singhania', memberCount: 3 },
  { id: 'team-08', tenantId: TENANT_ARQENSIAL_ID, departmentId: 'dept-accounts', departmentName: 'Accounts', name: 'Finance & Statutory Payroll', leadEmployeeId: 'emp-24', leadEmployeeName: 'Sunita Hegde', memberCount: 3 },
];

export const PRODUCTION_SHIFTS: Shift[] = [
  { id: 'shift-01', tenantId: TENANT_ARQENSIAL_ID, name: 'Mumbai Day Shift (Regular)', code: 'MUM-DAY', startTime: '09:30', endTime: '18:30', gracePeriodMinutes: 15, halfDayThresholdHours: 4.5, isRotational: false, assignedCount: 16 },
  { id: 'shift-02', tenantId: TENANT_ARQENSIAL_ID, name: 'Mira Road Shift', code: 'MIRA-DAY', startTime: '09:30', endTime: '18:30', gracePeriodMinutes: 15, halfDayThresholdHours: 4.5, isRotational: false, assignedCount: 9 },
  { id: 'shift-us-01', tenantId: TENANT_NORTHSTAR_ID, name: 'US East Coast Standard Shift', code: 'US-EST', startTime: '09:00', endTime: '17:30', gracePeriodMinutes: 10, halfDayThresholdHours: 4.0, isRotational: false, assignedCount: 18 },
  { id: 'shift-ae-01', tenantId: TENANT_VERTEX_ID, name: 'Dubai General Shift', code: 'DXB-GEN', startTime: '08:30', endTime: '17:30', gracePeriodMinutes: 15, halfDayThresholdHours: 4.0, isRotational: false, assignedCount: 14 },
  { id: 'shift-vv-retail', tenantId: TENANT_VASTRA_ID, name: 'Vastra Retail Store Shift (10:00 AM - 08:30 PM)', code: 'VV-RET', startTime: '10:00', endTime: '20:30', gracePeriodMinutes: 20, halfDayThresholdHours: 5.0, isRotational: false, assignedCount: 8 },
];

export const PRODUCTION_HOLIDAYS: Holiday[] = [
  // India (Arqensial)
  { id: 'hol-01', tenantId: TENANT_ARQENSIAL_ID, name: 'Republic Day', date: '2026-01-26', day: 'Monday', type: 'Mandatory', description: 'National Republic Day holiday' },
  { id: 'hol-02', tenantId: TENANT_ARQENSIAL_ID, name: 'Holi', date: '2026-03-04', day: 'Wednesday', type: 'Mandatory', description: 'Festival of Colours' },
  { id: 'hol-03', tenantId: TENANT_ARQENSIAL_ID, name: 'Gudi Padwa', date: '2026-03-19', day: 'Thursday', type: 'Mandatory', description: 'Maharashtra New Year' },
  { id: 'hol-04', tenantId: TENANT_ARQENSIAL_ID, name: 'Maharashtra Day', date: '2026-05-01', day: 'Friday', type: 'Mandatory', description: 'Maharashtra Statehood Day' },
  { id: 'hol-05', tenantId: TENANT_ARQENSIAL_ID, name: 'Independence Day', date: '2026-08-15', day: 'Saturday', type: 'Mandatory', description: 'National Independence Day' },
  { id: 'hol-06', tenantId: TENANT_ARQENSIAL_ID, name: 'Ganesh Chaturthi', date: '2026-09-14', day: 'Monday', type: 'Mandatory', description: 'Ganesh Festival Celebration' },
  { id: 'hol-07', tenantId: TENANT_ARQENSIAL_ID, name: 'Mahatma Gandhi Jayanti', date: '2026-10-02', day: 'Friday', type: 'Mandatory', description: 'Gandhi Jayanti observance' },

  // US (Northstar)
  { id: 'hol-us-01', tenantId: TENANT_NORTHSTAR_ID, name: "New Year's Day", date: '2026-01-01', day: 'Thursday', type: 'Mandatory', description: 'Federal holiday' },
  { id: 'hol-us-02', tenantId: TENANT_NORTHSTAR_ID, name: 'Memorial Day', date: '2026-05-25', day: 'Monday', type: 'Mandatory', description: 'National Memorial Day' },
  { id: 'hol-us-03', tenantId: TENANT_NORTHSTAR_ID, name: 'Independence Day', date: '2026-07-03', day: 'Friday', type: 'Mandatory', description: '4th of July Observed' },
  { id: 'hol-us-04', tenantId: TENANT_NORTHSTAR_ID, name: 'Labor Day', date: '2026-09-07', day: 'Monday', type: 'Mandatory', description: 'National Labor Day' },
  { id: 'hol-us-05', tenantId: TENANT_NORTHSTAR_ID, name: 'Thanksgiving Day', date: '2026-11-26', day: 'Thursday', type: 'Mandatory', description: 'Thanksgiving celebration' },

  // UAE (Vertex)
  { id: 'hol-ae-01', tenantId: TENANT_VERTEX_ID, name: 'New Year Day', date: '2026-01-01', day: 'Thursday', type: 'Mandatory', description: 'Official UAE holiday' },
  { id: 'hol-ae-02', tenantId: TENANT_VERTEX_ID, name: 'Eid al-Fitr', date: '2026-03-20', day: 'Friday', type: 'Mandatory', description: 'Eid al-Fitr holiday' },
  { id: 'hol-ae-03', tenantId: TENANT_VERTEX_ID, name: 'Arafat Day & Eid al-Adha', date: '2026-05-27', day: 'Wednesday', type: 'Mandatory', description: 'Eid al-Adha' },
  { id: 'hol-ae-04', tenantId: TENANT_VERTEX_ID, name: 'UAE National Day', date: '2026-12-02', day: 'Wednesday', type: 'Mandatory', description: 'Commemoration and National Day' },
];

export const PRODUCTION_SUBSCRIPTION_PLANS: SubscriptionPlan[] = [
  {
    id: 'managed_business',
    name: 'Managed Business Workspace',
    pricePerUserMonthly: 0,
    maxUsers: 999999,
    features: ['Employee Directory', 'Attendance & Geofencing', 'Leave Approvals', 'Payroll & Payslips', 'PostgreSQL RLS Isolation'],
    storageLimit: 'Unlimited',
    supportLevel: 'Dedicated ARQHR Administrator Support',
  },
  {
    id: 'managed_retail',
    name: 'Managed Retail & Store Operations',
    pricePerUserMonthly: 0,
    maxUsers: 999999,
    features: ['Store Floor & Sales Structure', 'Shift Scheduling & Grace Periods', 'Biometric & Selfie Attendance', 'Multi-tier Payroll & Tax', 'Expense Audits'],
    storageLimit: 'Unlimited',
    supportLevel: 'Dedicated ARQHR Administrator Support',
  },
  {
    id: 'managed_enterprise',
    name: 'Managed Multi-Branch Organization',
    pricePerUserMonthly: 0,
    maxUsers: 999999,
    features: ['Multi-Branch & Store Workspaces', 'Custom Role Hierarchy', 'Digital Employee ID Cards', 'Statutory Compliance & Form 16', 'Platform Audit Logs'],
    storageLimit: 'Unlimited',
    supportLevel: 'Dedicated ARQHR Administrator Support',
  },
];
